cxx_library(
    name = "teleopp",
    srcs = glob(["*.cpp"]),
    exported_headers = glob(["*.h"]),
    header_namespace = "teleopp",
    deps = [
        "//src/teleopp/fbs:fbs",
    ],
    visibility = ["PUBLIC"],
)

