cxx_test(
    name = "test",
    srcs = glob(["*.cpp"]),
    headers = glob(["*.h"]),
    deps = [
        "//src/teleopp:teleopp",
        "//src/teleopp/fbs:fbs",
        "//third-party:gtest",
        "//third-party:gmock",
    ],
)
